### ISSUE TITLE
"Working" always shown running 0.3.0, Passwords App 17.2, Owncloud 8.2.3

### ISSUE THREAD

**Issue by e-alfred** [eglia/ff-oc-passwords#10]
Hello,

I upgraded from Owncloud 8.1 to 8.2 and the Password app from 17 to 17.2 now I am getting this message in the browser console running 0.3.0:

`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data1 api.js:63:15`

If I click on the on the button of the extension the field next to "settings" is showing "working..." all the time. No passwords are shown. in the extension it says "0 logins in database".

If I click save in the settings pane I get this output on the console:

```
TypeError: browser is null nsLoginManagerPrompter.js:806:9
NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "browser is null" {file: "resource://gre/components/nsLoginManagerPrompter.js" line: 806}]'[JavaScript Error: "browser is null" {file: "resource://gre/components/nsLoginManagerPrompter.js" line: 806}]' when calling method: [nsILoginManagerPrompter::promptToSavePassword] LoginManagerParent.jsm:532:0
Die Zeichenkodierung des HTML-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Dokument oder Transferprotokoll deklariert werden. settings-panel.html
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data api.js:63:15
```

My browser is Firefox 45 on Kubuntu 14.04.

Thank you

**Comment by eglia** [comment]
The syntax error should be fixed in 0.3.1. For the rest I'm not sure if that belongs to my extension...

**Comment by e-alfred** [comment]
Well the other error comes from the file resource://ff-oc-passwords/data/settings-panel.html. The message in English:

```
A form was submitted in the windows-1252 encoding which cannot encode all Unicode characters, so user input may get corrupted. To avoid this problem, the page should be changed so that the form is submitted in the UTF-8 encoding either by changing the encoding of the page itself to UTF-8 or by specifying accept-charset=utf-8 on the form element. settings-panel.html
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. settings-panel.html
```

Any idea when 0.3.1 comes out? This is a real showstopper...

**Comment by eglia** [comment]
Ah I see, I didn't specify the character encoding. This is just a warning however and should cause no problems (for the moment).
0.3.1 is currently waiting to be signed by mozilla, I expect this to be done by tomorrow.

**Comment by e-alfred** [comment]
Okay thank you.
