### ISSUE TITLE
Self-signed certificate causes add-on to fail silently

### ISSUE THREAD

**Issue by codesmaker** [eglia/ff-oc-passwords#12]
Hi eglia,
Thanks a lot for your nice work.

I always get this message in the browser plugin. When I store store a username and password for a specific site, I also put the correct link to the login page in the field just before the username's. Am I missing something?

**Comment by eglia** [comment]
Does it say `X Logins in Database` with X>0? Are there any errors in the browser console? Did you click refresh in the addon after adding the login in ownCloud?

**Comment by codesmaker** [comment]
No. It only says "No Logins found for this site". I get this message when I click the Owncloud passwords icon plugin. I can't see any errors in the browser console. I have no refresh button in the addon. I've set refresh timers to 5 secs in the settings. The problem is that owncloud passwords doesn't detect sites and doesn't check against the database.

**Comment by eglia** [comment]
The firefox extension should look like this:
![screenshot](https://cloud.githubusercontent.com/assets/17555261/14470380/7a83f134-00e9-11e6-8d94-361069446e0f.png)
Does it not look like that for you?

In the settings panel, are all the "... site matching" settings checked?

5s refresh timer is probably a bit excessive, as it fetches all your passwords each time.

**Comment by codesmaker** [comment]
This is the firefox extension that I have:
![owncloud passwords](https://cloud.githubusercontent.com/assets/6999196/14495611/7f5f8950-0190-11e6-9bbf-5d422ca2d8f0.png)

Actually, "Include name field in site matching" is not checked but everything else is.

You're right. I just wanted to make sure that the database is up to date because I have been experimenting with many sites.

**Comment by eglia** [comment]
Hm... Does the button stay at "Working..." or does it change to "Refresh" after a moment? Maybe try a higher refresh timer.

**Comment by codesmaker** [comment]
Yes, it stays at "Working..." and it never changes. I changed the refresh timer to 120 but I still have the same issue.

**Comment by eglia** [comment]
Hm that is weird... Are you sure there are no errors in the browser console? (press CTRL+SHIFT+J and look for `ff-oc-passwords`).
I only see two options how this could happen, either there is some unhandled exception which should show up in the console, or the API call hangs for some reason. I added a timeout to git master, but that won't really solve your problem.
Please check if the API of your owncloud is working correctly, execute this in a terminal:
`curl -u [user] https://[owncloud]/index.php/apps/passwords/api/0.1/passwords`

**Comment by codesmaker** [comment]
I fairly believe that there are no messages about owncloud passwords (I press CTRL+SHIFT+J and filter the messages using "ff-oc-passwords") but I receive this error message:
mycloud:443 uses an invalid security certificate.
The certificate is not trusted because it is self-signed.
The certificate is not valid for any server names.
Error code: <a id="errorCode" title="SEC_ERROR_UNKNOWN_ISSUER">SEC_ERROR_UNKNOWN_ISSUER</a>

Can this cause pwncloud passwords to not connect to my owncloud server?

This is what I get when I check owncloud API:
[{"id":1,"user_id":"admin","loginname":"","website":"evernote.com\/login.action?targeturl=%2fhome.action","address":"","pass":"password","properties":"\"loginname\" : \"admin\", \"address\" : \"https:\/\/www.evernote.com\/login.action?targeturl=%2fhome.action\", \"strength\" : \"2\", \"length\" : \"8\", \"lower\" : \"1\", \"upper\" : \"0\", \"number\" : \"0\", \"special\" : \"0\", \"category\" : \"\", \"datechanged\" : \"2016-04-12\", \"notes\" : \"\"","notes":false,"creation_date":"1970-01-01","deleted":"0"},{"id":0,"user_id":"admin","loginname":null,"website":"admin","address":null,"pass":false,"properties":false,"notes":false,"creation_date":null,"deleted":null}]

But I had to use -k because of the self signed certificate I think no?

**Comment by eglia** [comment]
I did some testing and indeed using a self signed certificate causes the extension to silently fail. I added error notifications to git master.
The solution in my tests was to add a permanent exception in firefox for the domain.
When you normally open your owncloud, does firefox warn you about the certificate? If so, add an exception and make sure you check the "permanently store this exception" box.

**Comment by codesmaker** [comment]
I apologize for the late answer. I was really busy at work. It's solved. The self signed certificate was already added but it seems that there was a problem with it. I just deleted it and re added again and voilà. Thanks a lot for your help and quick responses. You rock man!

**Comment by eglia** [comment]
Ok great. Thanks for your feedback!
