### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by abishai** [eglia/ff-oc-passwords#16]
I installed plugin, but can't figure how to use it. I entered my credentials and got pop up window without header with 5 empty rectangles. 
If I click on key, I receive an empty bar.

FF 45.2.0/Windows XP

**Comment by abishai** [comment]
The following requests in server logs after I enter my password.
"GET /index.php/apps/passwords/api/0.1/version HTTP/1.1"
"GET /index.php/apps/passwords/api/0.1/passwords HTTP/1.1"

**Comment by eglia** [comment]
The main window should look like this:
![screenshot](https://cloud.githubusercontent.com/assets/17555261/14470380/7a83f134-00e9-11e6-8d94-361069446e0f.png)

If it doesn't, I'd say that something with your OS/Firefox is not working correctly. I'd strongly recommend to stop using Windows XP on a network, it is not safe anymore.
