### ISSUE TITLE
0 logins in database

### ISSUE THREAD

**Issue by f0ssie** [eglia/ff-oc-passwords#17]
Hi,
i've the following setup:

OS: Ubuntu 14.04.4 LTS
OC: 9.0.2
DB: Postgres 9.3.13
OC Passwords: v19-beta1
FF OC Passwords: 0.3.3

My problem is, that the FF addon always shows "0 logins in database", but obviously the connection to my oc server works, because when I login on a website, a little popup asks me, if I want to store this new login: ![newlogin](https://cloud.githubusercontent.com/assets/17596137/16268809/184cb6ca-3890-11e6-84e2-1f7950952c1c.png)
When I press the save button, the credentials are saved and I can see it in my owncloud Password App. But the counter never changes and I cannot use my stored passwords. I've already looked in the FF Console, but found no error message which belongs to ff-oc-passwords.

**Comment by ghost** [comment]
**Same happening here:** FreeBSD 10.3, Nextcloud 9.0.53, Mysql 5.6.30, Passwords v19-beta3.

**Comment by eglia** [comment]
This should be fixed in 0.3.4. Thanks for your reports!
