### ISSUE TITLE
Question: how does sync work with separate master password

### ISSUE THREAD

**Issue by fungs** [eglia/ff-oc-passwords#31]
I've set up the owncloud passwords extension with a separate master encryption password. When i run the the firefox add-on (where I cannot enter this second token), sync still works and new logins show up in the owncloud app. How does this work? Can it also retrieve logins or just push them?

**Comment by eglia** [comment]
The master password is not part of the en-/decryption process, it is only used to restrict access to the GUI. It has no influence on the API calls and therefore does not concern the firefox add-on.
