### ISSUE TITLE
OC Error: error token expired or app not enabled

### ISSUE THREAD

**Issue by tgutwin** [eglia/ff-oc-passwords#4]
After installing this plugin, entering loggin access info, it gets passwords successfully, and successfully works on various sites; However, 
I started repeatedly seeing the following error toast popup in My OC implementation at the top of the OC window : 
"**error token expired or app not enabled**". 
It was most noticeable when in the NEWS app simply scrolling down the news items, however I saw it in files app a few times.
This error is NOT present when this plugin is not enabled.

An older OC bug report tracked it it down to many calls to login() creating problems with expiring the token (?):
See [https://github.com/owncloud/core/issues/7707]

I am on OC 8.2.2  on Fedora 23 with apache 2.4.17 php 5.6.18
with FF 45.0.
I have the following OC apps installed: Calendar+, Activity, documents, Gallery+, News, music, Notes, Sketch, Passwords.
OC is accessed via SSL with a Lets's Encrypt Certificate.
tom

**Comment by eglia** [comment]
Should be fixed in 0.2.11
