### ISSUE TITLE
Add function to add new passwords when entered on a website

### ISSUE THREAD

**Issue by e-alfred** [eglia/ff-oc-passwords#6]
Hello,

a great feature would be the possibility to add user passwords to the Owncloud Passwords app using the extension. KeeFox (www.keefox.org) supports this by asking you to create a new entry into Keepass when entering a new password on a website password form. It saves the title of the website as well as the URL and username/password.

Thank you

**Comment by eglia** [comment]
With the next release of the password app, the api will be read-only (see [here](https://github.com/fcturner/passwords/blob/master/CHANGELOG.md)), so I can't add new entries.

**Comment by ghost** [comment]
I understand this, and would like that function too, but safety cannot be guaranteed if Firefox saves the username and password as plain text (which you state on your readme). One could delete all passwords or update them with false ones. 

I'm a bit uncertain about giving all rights thru an API. What do you both think about these things?

**Comment by eglia** [comment]
I see your point but I don't think it's a problem.
The addon only stores the owncloud username & password locally in the firefox password manager. As long as a master password is set, this data is encrypted on the disk. Everything else is handled in memory.

**Comment by ghost** [comment]
Allright. And can you encrypt that (and decrypt it on use)? A simple way in JavaScript is to make use of aes.js. The secret phrase could be something only the user of the browser has, not necessarily the owner of the computer. 
Or you could ask for the ownCloud password every time a user opens the browser. 
Or give users a choice, emphasising that Firefox saves prudent data locally. 
:smile:

**Comment by eglia** [comment]
I will add on option to not store the password so that it has to be entered on every browser start.

**Comment by e-alfred** [comment]
Well, KeeFox/KeePass do it that way:

https://github.com/luckyrat/KeeFox/wiki/en-|-Technical-|-KeePassRPC-detail#connection-security

They also say one should set a Firefox master password to make it more secure.

**Comment by ghost** [comment]
Great. I will open up the API again.

**Comment by thefirstofthe300** [comment]
I am going to architect my extension in a similar way to eglia so my extension shouldn't be vulnerable to someone accessing the ownCloud password via storage.  I would say that you can allow the API to create new password entries just fine.

**Comment by eglia** [comment]
This will be implemented in v0.3.0
