### ISSUE TITLE
Feature request: Improve domain search

### ISSUE THREAD

**Issue by tmaex** [eglia/ff-oc-passwords#8]
It would be fantastic if your plugin just shows credetials for the correct website:
- If the domain is stored with https://example.org don't show creds. at http://example.org
- If the domain is stored with sub.example.org don't show creds at example.org
- If the domain is stored with sub.example.org don't show creds at sub2.example.org
- If the domain is stored with example.org/path/ don't show creds at example.org/
- If the domain is stored with example.org/path/ don't show creds at example.org/path2/

**Comment by eglia** [comment]
I personally prefer it the way it is now, but I'll look into adding some configuration options to change the behaviour.

**Comment by eglia** [comment]
The next version will include settings to:
- ignore/enforce the protocol
- ignore/enforce subdomains
- ignore/enforce path
