### ISSUE TITLE
Unable to access plugin configuration

### ISSUE THREAD

**Issue by ksmolder** [eglia/ff-oc-passwords#9]
Running version 0.30 from Mozilla addons on Firefox 45.0, Ubuntu 14.04.

After installing the plugin, I see no way to access the configuration settings of this plugin.
- When clicking the preferences button in the Add-ons Manager list, it takes me to the same overview as the "More" link would do
- I do not see any added settings in the main Firefox preferences page

How can one setup this plugin?

**Comment by eglia** [comment]
There should be a button in your toolbar with [this](https://github.com/eglia/ff-oc-passwords/blob/master/data/app_black.png) icon. On your first launch, this will directly open the settings panel. Later it will open the main panel, which has a button to access the settings.

**Comment by ksmolder** [comment]
Indeed, must have overlooked that one...
May I suggest to move this dialogue to the Preferences section of the add-on overview? You normally set this information only once, so assigning a toolbar button to it feels like a little bit overkill...

Thanks for the plugin!!

**Comment by eglia** [comment]
Well the toolbar button is how you use the extension (fill forms etc.), it's not just for the settings. I don't think it's unreasonable to add a single toolbar button to control the extension.
